export default {
  primary: "#496D96",
  darkPrimary: "#3D5169",
  secondary: "#559898",
  third: "#CCEEEF",
  darkThird: "#AACCEE",
  background: "#FFFFFA",
  diffColor: "#C5B78A",
  menuBarBackground: "#F1F3F4",
  formBackround: "#EEEEE0",
  textPrimary: "black",
  textSecondary: "#949494",
  black: "black",
  white: "#FFFFFF",
  errorColor: "red",
};
