export default {
  primary: "#0D652D",
  secondary: "#34A853",
  third: "#B0FFB0",
  background: "#FFFFFA",
  formBackround: "#EEEEE0",
  menuBarBackground: "#F1F3F4",
  textPrimary: "black",
  textSecondary: "#949494",
  black: "black",
  white: "#FFFFFF",
  errorColor: "red",
  menuBorder: "#9AA0A6",
  menuTopBorder: "#0D652D",
  menuHighlightBorder: "#0D652D",
  menuHighlightBG: "#34A853",
  dataCircleBorder: "#34A853",
  cardBackGround: "#AADDAA", // CEEAD6
  loadinAnimationColor: "#174EA6",
  checkBoxColor: "#174EA6",
  CHART: {
    background: "#FFFFFA",
    gradientFrom: "#0D652D",
    gradientTo: "#34A853",
    stroke: "#B0FFB0",
    dateSelectorBG: "#E3E3E3",
    dateSelectorHighlight: "#BCBCBC",
  },
};
