export default {
  primary: "#34A853",
  secondary: "#",
  background: "#D2E3FC",
  menuBarBackground: "#CEEAD6",
  textPrimary: "black",
  textSecondary: "#949494",
  black: "black",
  errorColor: "red",
  menuBorder: "#9AA0A6",
  menuTopBorder: "#0D652D",
  menuHighlightBorder: "#0D652D",
  menuHighlightBG: "#F1F3F4",
  dataCircleBorder: "#34A853",
  dataTextBorder: "#CEEAD6",
};
