export default {
  loginApiUrl: "https://atc.takacsnet.hu/CONTROLS/login.php",
  home: "Home",
  login: "Log in",
  welcome: "Welcome",
  aquariums: "Aquariums",
  configs: "Configurations",
  statistics: "Statistics",
  profile: "Profile",
  settings: "Settings",
  regitration: "Registration",
  signup: "Sign up",
  or: "Or",
  emailInputPlaceholder: "Your email address",
  passInputPlaceHolder: "Your password",
  missingEmailError: "Missing email address!",
  missingPasswordError: "Missing password!",
  invalidEmailError: "Invalid email address!",
  successfulLogin: "Successful login!",
};
