export default {
  expoProjectId: "9d33dc99-5dc7-4cbf-9fa8-8b351cd1b878",
  loginApiUrl: "https://atc.takacsnet.hu/CONTROLS/login.php",
  registrationApiUrl: "https://atc.takacsnet.hu/CONTROLS/register.php",
  tokenLoginApiUrl: "https://atc.takacsnet.hu/CONTROLS/loginWithToken.php",
  projetName: "ATC - Aquarium Manager",
  home: "Home",
  aquariumSelctorPlaceholder: "Select your aquarium",
  searchByName: "Search by name",
  status: "Status",
  currentFishCount: "Number of fish",
  login: "Log in",
  welcome: "Welcome",
  aquariums: "Aquariums",
  configs: "Configs",
  statistics: "Stats",
  profile: "Profile",
  settings: "Settings",
  registration: "Registration",
  info: "Information",
  cancel: "Cancel",
  signup: "Sign up",
  confirm: "Confirm",
  rememberMe: "Remember me",
  or: "Or",
  temperature: "Temperature",
  ph: "Ph",
  waterLevel: "Water Level",
  light: "Light",
  name: "Name",
  length: "Length",
  height: "Height",
  width: "Width",
  outlet1: "Outlet 1",
  outlet2: "Outlet 2",
  outlet3: "Outlet 3",
  min: "Min.",
  max: "Max.",
  on: "On",
  off: "Off",
  feeding: "Feeding",
  time: "Time",
  portions: "Portions",
  edit: "Edit",
  configEditLabel: "Edit the configuration of ",
  emailInputPlaceholder: "Your email address",
  passInputPlaceHolder: "Your password",
  passAgainInputPlaceholder: "Your password again",
  firstNameInputPlaceholder: "Your first name",
  lastNameInputPlaceholder: "Your last name",
  aquariumIdInputPlaceholder: "Your aquarium's id",
  missingEmailError: "Missing email address!",
  missingPasswordError: "Missing password!",
  missingFirstNameError: "Missing first name!",
  missingLastNameError: "Missing last name!",
  missingAquariumIdError: "Missing aquarium ID!",
  passwordsNotMatchError: "Passwords does not match!",
  shortPasswordError: "Password should be least 8 characters long!",
  invalidAquariumIdError: "Invalid aquarium ID!",
  invalidEmailError: "Invalid email address!",
  successfulLogin: "Successful login!",
  successfulSignup: "Successfully signed up!",
  unexpectedStatusErrorMessage: "Unexpected error occured! Response status: ",
  pushNotificationsDeniedAlertMessage:
    "Push notifications are disabled! You won't get notifications about your aquarium's status!",
  noDeviceTokenString: "NO_DEVICE_TOKEN",
};
